# Generated by Django 2.1.1 on 2018-10-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
