# Generated by Django 2.1.2 on 2018-10-13 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 13, 18, 25, 40, 69990)),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 13, 18, 25, 40, 69561), null=True),
        ),
    ]
