# Generated by Django 2.1.1 on 2018-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_due_on', models.DateTimeField()),
                ('owner', models.CharField(max_length=50)),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
    ]
